image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

tasks:
  - init: |
      export EDITOR="command gp open -w" VISUAL="command gp open -w"
      cp -f /workspace/playground/template.zshrc ~/.zshrc
    command: exec zsh

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - golang.go
